/**
 * This file used to be the one generated by the React Native command line
 * Its content has been moved to `src/RNDemoApp/RNDemoApp.tsx`
 *
 * Now this file is only another entry point before our component tree
 */

import React from 'react';
import {Main} from './src/main';

const App = () => {
  return <Main />;
};

export default App;
